/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

/*
 * File: MusicLibrary.framework/MusicLibrary
 * Arch: PowerPC 7400 (ppc7400)
 *       Current version: 18.0.0, Compatibility version: 1.0.0
 */

@interface MLPhotoDCFObject : NSObject
{
    NSString *_name;
    int _number;
}

+ (id)validDCFNameForName:(id)fp8 requiredLength:(int)fp12 nameLength:(int)fp16 number:(int *)fp20 numberRange:(struct _NSRange)fp24;
- (id)initWithName:(id)fp8 number:(int)fp12;
- (void)dealloc;
- (id)name;
- (int)number;
- (int)compare:(id)fp8;
- (id)description;

@end

@interface MLPhoto : NSObject
{
    int _imageID;
}

- (id)initWithImageID:(int)fp8;
- (int)imageID;

@end

@interface MLPhotoAlbum : NSObject
{
    int _albumID;
    NSString *_albumName;
    NSMutableArray *_images;
    id _posterImage;
    BOOL _isLibrary;
    unsigned long long _playlistID;
    unsigned long long _songID;
}

+ (id)libraryAlbum;
- (id)initWithAlbumID:(unsigned int)fp8 albumName:(id)fp12;
- (void)dealloc;
- (id)description;
- (id)_posterImage;
- (void)_setPosterImage:(id)fp8;
- (unsigned int)albumID;
- (id)name;
- (void)setName:(id)fp8;
- (BOOL)isLibrary;
- (void)setLibrary:(BOOL)fp8;
- (BOOL)isEmpty;
- (id)images;
- (void)setImages:(id)fp8;
- (void)addImage:(id)fp8;
- (void)removeImage:(id)fp8;
- (id)imageWithImageID:(int)fp8;
- (int)count;
- (void)deleteImageAtIndex:(int)fp8;
- (unsigned long long)slideshowPlaylistID;
- (void)setSlideshowPlaylistID:(unsigned long long)fp8;
- (unsigned long long)slideshowSongID;
- (void)setSlideshowSongID:(unsigned long long)fp8;

@end

@interface MLPhotoLibrary : NSObject
{
    NSString *_path;
    NSMutableArray *_albums;
}

+ (id)sharedPhotoLibrary;
+ (id)imageFormats;
+ (int)widthForFormat:(int)fp8;
+ (int)heightForFormat:(int)fp8;
+ (BOOL)formatIsCropped:(int)fp8;
- (void)_loadImageLibrary;
- (void)_flushImageLibrary;
- (id)initWithPath:(id)fp8;
- (void)dealloc;
- (id)dataForPhoto:(id)fp8 format:(int)fp12 width:(int *)fp16 height:(int *)fp20 bytesPerRow:(int *)fp24 dataWidth:(int *)fp28 dataHeight:(int *)fp32 imageDataOffset:(int *)fp36;
- (id)_albums;
- (void)_setAlbums:(id)fp8;
- (id)albums;
- (void)flushAlbums;
- (void)reloadAlbums;
- (id)_imagesForAlbum:(id)fp8 firstImageOnly:(BOOL)fp12;
- (int)numberOfImagesInAlbum:(id)fp8;
- (int)countOfAllPhotos;
- (id)firstImageForAlbum:(id)fp8;
- (id)imagesForAlbum:(id)fp8;

@end

@interface MLPhotoDCIMDirectory : NSObject
{
    NSString *_dcimPath;
    NSString *_miscPath;
    NSString *_posterImagePath;
    NSMutableArray *_topLevelDirectories;
    struct __CFDictionary *_topLevelDirectoriesByNumber;
    struct __CFSet *_unusableTopLevelDirectoryNumbers;
    int _lastUsedDirectoryNumber;
    NSMutableDictionary *_userInfo;
    BOOL _userInfoDidChange;
}

- (id)_userInfoPath;
- (id)initWithDCIMPath:(id)fp8;
- (void)dealloc;
- (id)dcimPath;
- (id)miscPath;
- (id)posterImagePath;
- (void)saveUserInfo;
- (id)userInfo;
- (id)userInfoObjectForKey:(id)fp8;
- (void)setUserInfoObject:(id)fp8 forKey:(id)fp12;
- (id)dcfDirectories;
- (void)clearDCFDirectories;
- (id)nextAvailableDirectory;
- (int)countOfAllPhotos;

@end

@interface MLPhotoDCFDirectory : MLPhotoDCFObject
{
    MLPhotoDCIMDirectory *_dcimDirectory;
    struct __CFDictionary *_fileGroupsByNumber;
    int _maxFileGroupNumber;
    int _lastUsedFileGroupNumber;
}

- (id)_lastUsedFileGroupUserInfoKey;
- (id)initWithName:(id)fp8 number:(int)fp12 dcimDirectory:(id)fp16;
- (void)dealloc;
- (id)dcimDirectory;
- (BOOL)_canAddImageWithMinimumFileGroupNumber:(int)fp8;
- (BOOL)canAddImage;
- (id)fullPath;
- (void)ensureDirectoryExists;
- (id)fileGroups;
- (id)nextAvailableFileGroup;
- (void)removeFileGroup:(id)fp8;

@end

@interface MLPhotoDCFFileGroup : MLPhotoDCFObject
{
    id _delegate;
    MLPhotoDCFDirectory *_directory;
    NSMutableSet *_extensions;
    NSDate *_date;
    NSString *_preferredExtension;
}

- (id)initWithName:(id)fp8 number:(int)fp12 directory:(id)fp16;
- (void)dealloc;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)directory;
- (id)imageSourceTypeHint;
- (BOOL)isValid;
- (void)addExtension:(id)fp8;
- (id)date;
- (void)setDate:(id)fp8;
- (int)compare:(id)fp8;
- (id)description;
- (id)pathForFullSizeImage;
- (id)pathForThumbnailFile;
- (id)pathForLowResolutionFile;

@end



