/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

/*
 * File: TelephonyUI.framework/TelephonyUI
 * Arch: PowerPC 7400 (ppc7400)
 *       Current version: 1.0.0, Compatibility version: 1.0.0
 */

#import "UIThreePartButton.h"

@interface TPPushButton : UIThreePartButton
{
    NSString *_plusSeparatedTitle;
    int _tpcolor;
    float _titleImagePadding;
    float _titleImageRightMargin;
    float _titleVerticalOffset;
    float _iconVerticalOffset;
    float _iconAlpha;
    float _minimumFontSize;
}

+ (float)defaultHeight;
+ (float)defaultHeightForColor:(int)fp8;
+ (void)preloadImagesForColor:(int)fp8;
+ (id)answerButtonImage;
+ (id)declineButtonImage;
- (float)minTitleMargin;
- (CDAnonymousStruct1)_buttonSlices;
- (id)initWithTitle:(id)fp8 icon:(id)fp12 color:(int)fp16 frame:(struct CGRect)fp20;
- (void)dealloc;
- (void)setPlusSeparatedTitle:(id)fp8;
- (void)setPushButtonColor:(int)fp8;
- (int)pushButtonColor;
- (float)titleImagePadding;
- (void)setTitleImagePadding:(float)fp8;
- (void)setTitleImageRightMargin:(float)fp8;
- (void)setTitleVerticalOffset:(float)fp8;
- (void)setIconVerticalOffset:(float)fp8;
- (void)setIconAlpha:(float)fp8;
- (void)drawImageAtPoint:(struct CGPoint)fp8 fraction:(float)fp16;
- (void)drawTitleAtPoint:(struct CGPoint)fp8 width:(float)fp16;
- (struct CGPoint)_titleOriginForTitleSize:(struct CGSize)fp8;
- (void)drawButtonPart:(int)fp8 inRect:(struct CGRect)fp12;
- (void)setMinimumTitleFontSize:(float)fp8;

@end

@interface TPBottomBar : UIView
{
}

+ (id)_backgroundImage;
+ (void)preloadImages;
+ (float)defaultHeight;
- (id)initWithDefaultSize;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end


@interface TPBottomButtonBar : TPBottomBar
{
    id _delegate;
    TPPushButton *_button;
}

- (id)initForIncomingCallWaitingWithFrame:(struct CGRect)fp8;
- (id)initForEndCallWithFrame:(struct CGRect)fp8;
- (id)initForTTYWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setButton:(id)fp8;
- (id)button;

@end

@interface TPBottomDualButtonBar : TPBottomButtonBar
{
    TPPushButton *_button2;
    unsigned int _drawSeparator:1;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (id)initForIncomingCallWithFrame:(struct CGRect)fp8;
- (id)initForCallFailureWithFrame:(struct CGRect)fp8;
- (id)initForEmergencyCallWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (float)_buttonWidth;
- (void)_updateButtonSettings:(id)fp8;
- (void)setButton:(id)fp8;
- (void)setButton2:(id)fp8;
- (id)button2;
- (void)setDrawsSeparateWells:(BOOL)fp8;
- (void)drawRect:(struct CGRect)fp8;


@end

