/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

/*
 * File: ../Frameworks/UIKit.framework/UIKit
 * Arch: PowerPC 7400 (ppc7400)
 *       Current version: 747.19.0, Compatibility version: 1.0.0
 */

#import "UIPushButton.h"

@interface UIThreePartButton : UIPushButton
{
    CDAnonymousStruct8 _bkgndSlices;
}

+ (id)defaultFont;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setBackgroundSlices:(CDAnonymousStruct8)fp8;
- (void)setBackgroundImage:(id)fp8;
- (void)setPressedBackgroundImage:(id)fp8;
- (id)background;
- (CDAnonymousStruct8)_backgroundSlices:(struct CGSize)fp8;
- (float)minTitleMargin;
- (void)drawTitleAtPoint:(struct CGPoint)fp8 width:(float)fp16;

@end

